
[window]
dimensions = { columns = 150, lines = 30 }
padding = { x = 8, y = 8 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font" }
size = 10

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
blink_timeout = 0

[mouse]
hide_when_typing = true

[terminal]
shell = { program = "pwsh", args = ["-NoLogo",] }

